/**
 * Centralized Error Codes
 * Provides consistent error codes across the application
 */

/**
 * Error code enum for consistent error handling
 */
export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUERY_TOO_COMPLEX = 'QUERY_TOO_COMPLEX',
  QUERY_COST_EXCEEDED = 'QUERY_COST_EXCEEDED',
  QUERY_DEPTH_EXCEEDED = 'QUERY_DEPTH_EXCEEDED',
  INPUT_SIZE_EXCEEDED = 'INPUT_SIZE_EXCEEDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
}
